uint16 temperature				# battery monitor sensor temperature report in [0.1 K]
uint16 voltage					# battery monitor sensor voltage report in [mV]
int16  current					# battery monitor sensor current report in [mA]
uint8  stateofcharge			# battery monitor sensor state of charge in [%]
uint16 batterystatus			# battery monitor sensor battery status report in [Hex]
uint16 serialnumber				# battery monitor sensor serial number report in [Hex]
uint32 safetystatus				# battery monitor sensor safety status report in [Hex]
uint32 operationstatus			# battery monitor sensor operation status report in Hex
uint16[15] cellvoltage			# battery monitor sensor N cell voltage report in [mV]