uint8 pwr_brd_status			# power boards status register
uint8 pwr_brd_led_status		# power boards power leds status
uint8 pwr_brd_blink_reg			# power boards blink register, defines number of blinks and interval
uint8 pwr_brd_led_1_pwr			# power boards power led 1 intensity in percentage
uint8 pwr_brd_led_2_pwr			# power boards power led 2 intensity in percentage
uint8 pwr_brd_led_3_pwr			# power boards power led 3 intensity in percentage
uint8 pwr_brd_led_4_pwr			# power boards power led 4 intensity in percentage
float32 pwr_brd_system_volt		# power boards system voltage in volts
float32 pwr_brd_servo_volt		# power boards servo voltage in volts
float32 pwr_brd_mot_l_amp		# power boards left motor port current in amperes
float32 pwr_brd_mot_r_amp		# power boards right motor port current in amperes
float32 pwr_brd_digital_amp		# power boards digital channel current in amperes
float32 pwr_brd_analog_amp		# power boards analog channel current in amperes
float32 pwr_brd_ext_amp		    # power boards extension port current in amperes
float32 pwr_brd_digital_volt	# power boards digital voltage in volts
float32 pwr_brd_aux_amp			# power boards aux port current in amperes